### ISSUE TITLE
olat_1  | /bin/bash: /entrypoint.sh: Permission denied

### ISSUE THREAD

**Issue by mclark4386** [BlackRose01/docker-openolat#1]
I'm guessing that the script isn't set to executable in the repo? just tried pulling it from docker hub and running it with this docker-compose file to try it out:

```
version: "3.1"

services: 
  olat:
    image: blackrose01/openolat:latest
    environment:
      DB_TYPE: postgresql
      DB_HOST: db
      DB_NAME: olat
      DB_USER: postgres
      DB_PASS: postgres
    ports:
      - "8088:8088"
    volumes:
      - ./olat_data:/opt/openolat/olatdata

  db:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: olat
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
```

If I'm doing it wrong would love to know how! Thanks!^^
